# Generated by Django 6.0.3 on 2026-04-08 08:00

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefile',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Эталон'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tree_id', 'lft'], name='blog_comment_tree_id_lft_idx'),
        ),
    ]
