# Generated by Django 6.0.3 on 2026-04-08 10:51

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import modules.blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articlefile_options_alter_article_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='general_works/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'pdf')), modules.blog.models.validate_file_size], verbose_name='Файл с бланком')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Результаты обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Обработано'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='general_works', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Общая работа',
                'verbose_name_plural': 'Общие работы',
                'db_table': 'app_general_works',
                'ordering': ['-created_at'],
            },
        ),
    ]
