# Generated by Django 6.0.3 on 2026-04-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_general_file_article_general_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='general_file',
        ),
    ]
